version: '3.3'

services:
  web:
    container_name: server_backend
    build: ./app
    command: watchmedo auto-restart --recursive -d . -p '*.py' -- python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  telegram-bot:
    build: ./app
    command: watchmedo auto-restart --recursive -d . -p '*.py' -- python3 manage.py telegram_bot
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  celery:
    build: ./app
    command: watchmedo auto-restart --recursive -d . -p '*.py' -- celery -A server.celery worker --beat --loglevel=info
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"

volumes:
  postgres_data:
