# Generated by Django 3.1.2 on 2022-04-15 13:11

from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("telethon_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telethonaccount",
            name="api_hash",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Telegram api hash"
            ),
        ),
        migrations.AlterField(
            model_name="telethonaccount",
            name="api_id",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Telegram api id"
            ),
        ),
        migrations.AlterField(
            model_name="telethonaccount",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True, verbose_name="Номер телефона"
            ),
        ),
    ]
