# Generated by Django 3.1.2 on 2022-04-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telethon_app", "0002_auto_20220415_1311"),
    ]

    operations = [
        migrations.AddField(
            model_name="telethonaccount",
            name="date_of_last_deactivate",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последней деактивации"
            ),
        ),
        migrations.AddField(
            model_name="telethonaccount",
            name="reason_of_last_deactivate",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Причина последней деактивации",
            ),
        ),
    ]
