# Generated by Django 3.1.2 on 2022-04-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telethon_app", "0003_auto_20220418_1632"),
    ]

    operations = [
        migrations.AddField(
            model_name="telethonaccount",
            name="is_busy",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Занят работой?"
            ),
        ),
    ]
