# Generated by Django 3.1.2 on 2022-05-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telethon_app", "0004_telethonaccount_is_busy"),
    ]

    operations = [
        migrations.AddField(
            model_name="telethonaccount",
            name="is_permanent_banned",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Забанен навсегда?"
            ),
        ),
    ]
