# Generated by Django 3.2.8 on 2021-10-07 13:37

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Создан",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Изменен",
                    ),
                ),
                ("chat_id", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("message_id", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name": "Telegram сообщение",
                "verbose_name_plural": "Telegram сообщения",
            },
        ),
    ]
