# Generated by Django 3.2.8 on 2021-10-09 16:56

from django.db import migrations

categories = [
    "Кафе и рестораны",
    "Машина",
    "Образование",
    "Отдых и развлечения",
    "Платежи, комиссии",
    "Подарки",
    "Покупки: одежда, техника",
    "Продукты",
    "Проезд",
    "Забота о себе",
]


def populate_categories(apps, schema_editor):
    Category = apps.get_model("telegram_bot", "Category")

    for category in categories:
        Category.objects.get_or_create(
            title=category,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_bot", "0002_category_expenditure"),
    ]

    operations = [
        migrations.RunPython(populate_categories),
    ]
