# Generated by Django 3.2.8 on 2021-10-09 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telegram_bot", "0003_auto_20211009_1656"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expenditure",
            options={"verbose_name": "Трат", "verbose_name_plural": "Траты"},
        ),
        migrations.AddField(
            model_name="expenditure",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
