# Generated by Django 3.2.8 on 2021-10-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0004_auto_20211009_1743"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expenditure",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="expenditure",
            name="title",
        ),
    ]
