# Generated by Django 3.2.8 on 2021-10-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0005_auto_20211009_1811"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenditure",
            name="value",
            field=models.PositiveIntegerField(verbose_name="Сумма траты"),
        ),
    ]
