# Generated by Django 3.2.8 on 2021-10-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0006_alter_expenditure_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expenditure",
            name="category",
        ),
        migrations.RemoveField(
            model_name="expenditure",
            name="user",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Expenditure",
        ),
    ]
