# Generated by Django 4.0 on 2021-12-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0007_auto_20211013_0914"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["my_order"],
                "verbose_name": "Telegram сообщение",
                "verbose_name_plural": "Telegram сообщения",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
