# Generated by Django 3.1.2 on 2022-04-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telethonaccount",
            name="is_initialized",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Инициализирован?"
            ),
        ),
    ]
