# Generated by Django 3.1.2 on 2022-04-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_inviteorder"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TelethonAccount",
        ),
    ]
