# Generated by Django 3.1.2 on 2022-04-15 21:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_delete_telethonaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inviteorder",
            name="affected_users",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128), default=list, size=None
            ),
        ),
    ]
