# Generated by Django 3.1.2 on 2022-04-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_auto_20220415_2126"),
    ]

    operations = [
        migrations.AddField(
            model_name="inviteorder",
            name="in_progress",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Занят работой?"
            ),
        ),
    ]
