# Generated by Django 3.1.2 on 2022-04-25 14:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_inviteorder_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteorder',
            name='in_progress',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В процессе выполнения?'),
        ),
        migrations.CreateModel(
            name='SpamOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активная?')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Создан')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Изменен')),
                ('spam_message', models.CharField(max_length=1000, verbose_name='spam message')),
                ('donor_chat_link', models.CharField(max_length=128, verbose_name='donor chat link')),
                ('affected_users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=list, size=None)),
                ('in_progress', models.BooleanField(db_index=True, default=False, verbose_name='В процессе выполнения?')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
