# Generated by Django 3.1.2 on 2022-04-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telethon_app", "0004_telethonaccount_is_busy"),
        ("orders", "0007_auto_20220427_2136"),
    ]

    operations = [
        migrations.AddField(
            model_name="inviteorder",
            name="telethon_accounts",
            field=models.ManyToManyField(to="telethon_app.TelethonAccount"),
        ),
    ]
