# Generated by Django 3.1.2 on 2022-04-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telethon_app", "0004_telethonaccount_is_busy"),
        ("orders", "0008_inviteorder_telethon_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inviteorder",
            name="telethon_accounts",
            field=models.ManyToManyField(
                related_name="orders", to="telethon_app.TelethonAccount"
            ),
        ),
    ]
