# Generated by Django 3.1.2 on 2022-05-05 14:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telethon_app", "0004_telethonaccount_is_busy"),
        ("orders", "0009_auto_20220427_2253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inviteorder",
            name="affected_users",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="inviteorder",
            name="telethon_accounts",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to="telethon_app.TelethonAccount"
            ),
        ),
    ]
