# Generated by Django 3.1.2 on 2022-05-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_auto_20220505_1403"),
    ]

    operations = [
        migrations.AddField(
            model_name="inviteorder",
            name="get_recently_online_users",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="inviteorder",
            name="was_online_user_delta",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
