# Generated by Django 3.1.2 on 2022-04-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telethon_app', '0004_telethonaccount_is_busy'),
        ('orders', '0010_auto_20220429_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteorder',
            name='telethon_accounts',
            field=models.ManyToManyField(related_name='invite_orders', to='telethon_app.TelethonAccount'),
        ),
    ]
