# Generated by Django 3.1.2 on 2022-03-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Telegram id"
            ),
        ),
    ]
