# Generated by Django 3.2.6 on 2021-12-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активная?"
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "telegram_user_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "telegram_chat_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
