# Generated by Django 4.0 on 2021-12-25 17:41

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активная?"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
                ("feature", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="")),
                ("sum", models.PositiveIntegerField()),
                ("days", models.PositiveSmallIntegerField()),
                ("interestRate", models.CharField(max_length=255)),
                ("time", models.CharField(max_length=255)),
                ("offerId", models.PositiveIntegerField()),
                ("my_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Предложение МФО",
                "verbose_name_plural": "Предложения МФО",
                "ordering": ["my_order"],
            },
        ),
    ]
