# Generated by Django 4.0 on 2021-12-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="logo",
            field=models.ImageField(upload_to="offer-logos"),
        ),
    ]
